name: pytram-env
channels:
  - conda-forge
  - anaconda
dependencies:
  - python>=3.7
  - anaconda
  - numpy>=1.16.2
  - scikit-learn
  - scipy>=1.2.1
  - sphinx=>1.8.4
  - matplotlib
  - progressbar2